export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_ARTICLE = "SET_CURRENT_ARTICLE";
export const SET_CURRENT_COMMENTS = "SET_CURRENT_COMMENTS";
